liquidacion/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.views.i18n import JavaScriptCatalog

from liquidacion.views import *
from . import views

app_name = 'liquidacion'

urlpatterns = [
    #path('accounts/login/', 'django.contrib.auth.views.login', name='login'),
    #path('accounts/logout/', 'django.contrib.auth.views.logout', name='logout'),
    path('home/', views.index, name='index'),
    path('opciones_proceso', views.opciones_proceso, name='opciones_proceso'),
    path('opciones_vacaciones', views.opciones_vacaciones, name='opciones_vacaciones'),
    path('opciones_reportes', views.opciones_reportes, name='opciones_reportes'),
    path('funcionario/<int:idfuncionario>/movimiento/nuevo/', views.movimiento_vista, name='nuevo_movimiento'),
    path('movimiento_padre/<int:idpadre>/', views.movimiento_vista, name='modificar_movimiento'),
    path('movimiento/<int:idmovimiento>', views.movimiento_vista, name='editar_movimiento'),
    path('buscar_funcionario', views.busqueda_funcionarios, name='buscar_funcionario'),
    path('buscar_movimiento', views.busqueda_movimiento_funcionario, name='buscar_movimiento'),
    path('get_movimientos', views.get_movimientos, name='get_movimientos'),
    path('movimiento/<int:idmovimiento>/documento/nuevo/', views.documento_vista, name='nuevo_documento'),
    path('movimiento/<int:idmovimiento>/documento/<int:iddocumento>', views.documento_vista, name='ver_documento'),
    path('movimiento/<int:idmovimiento>/constante/nuevo/', views.constante_vista, name='nueva_constante'),
    path('movimiento/<int:idmovimiento>/constante/<int:idconstante>', views.constante_vista, name='borrar_constante'),
    path('categoriasalarial-list', CategoriaSalarialList.as_view(), name='categoriasalarial-list'),
    path('objetodegasto/add/', ObjetoDeGastoCreate.as_view(), name='objetodegasto-add'),
    path('tipomovimiento/add/', TipoMovimientoCreate.as_view(), name='tipomovimiento-add'),
    path('movimientomotivo/add/', MovimientoMotivoCreate.as_view(), name='movimientomotivo-add'),
    path('success_page/<int:idmovimiento>/', views.success_page, name='success_page'),
    path('movimiento_resumen/<int:idmovimiento>/', views.mostrar_movimiento_resumen, name='movimiento_resumen'),
    path('ajax/traer_tipomovimientos/', views.traer_tipomovimientos, name='traer_tipomovimientos'),
    path('ajax/traer_og/', views.traer_og, name='traer_og'),
    path('ajax/traer_variables/', views.traer_variables, name='traer_variables'),
    path('ajax/traer_constantes/', views.traer_constantes, name='traer_constantes'),
    path('ajax/traer_motivomovimientos/', views.traer_motivomovimientos, name='traer_motivomovimientos'),
    path('buscarmovimientofuncionario/', views.buscar_movimientos_funcionario, name='buscar_movimientos_funcionario'),
    path('movimiento/<int:idmovimiento>/pago/nuevo/', views.pago_vista, name='nuevo_pago'),
    path('liquidacionm/seleccion/', views.parametros_liq_mensual, name='parametros_liq_mensual'),
    path('ajax/traer_departamentos/', views.traer_departamentos, name='traer_departamentos'),
    path('ajax/traer_funcionarios/', views.traer_funcionarios, name='traer_funcionarios'),
    path('liqpendientes/dpto/<int:iddpto>/mes/<int:mes>/anho/<int:anho>/', views.liq_pendientes_list, name='liq_pendientes_list'),
    path('editar_liquidacion/<int:idliquidacion>/', views.vista_liq_mensual, name='editar_liquidacion'),
    path('liquidacion_haber/<int:idliquidacionhaber>/', views.vista_liquidacionhaber, name='editar_liquidacionhaber'),
    path('liquidacionhaber/<int:idliquidacionhaber>/detalle/nuevo/', views.vista_detalleliquidacion, name='detalleliquidacion-add'),
    path('liquidacionhaber/<int:idliquidacionhaber>/detalle/<int:iddetalleliq>', views.vista_detalleliquidacion,
         name='detalleliquidacion-edit'),
    path('detalle/<int:pk>/delete/', views.delete_detalleliquidacion, name='detalleliquidacion-delete'),
    path('carga_vacaciones/', views.vacaciones_form, name='cargar_vacaciones'),
    path('liquidacion/pendientes/', views.liq_pendientes_filtro, name='liq_pendientes_filtro'),
    path('liqpendientes/funcionario/<int:funcionario>/mes/<int:mes>/', views.liq_funcionarios_list, name='liq_funcionarios_list'),
    path('ajax/traer_mes/', views.traer_mes, name='traer_mes'),
    path('liquidaciones/periodo/', views.liquidaciones_periodo, name='liquidaciones_periodo'),
    path('confirmar_liquidaciones/', views.confirmar_liquidaciones, name='confirmar_liquidaciones'),
    path('consulta_vacaciones/', views.consulta_vacaciones, name='consulta_vacaciones'),
    path('liquidaciones/confirmadas/periodo/', views.confirmadas_periodo, name='confirmadas_periodo'),
    path('liquidaciond/seleccion/', views.param_liq_definitiva, name='param_liq_definitiva'),
    path('liquidacion_baja/movimiento/<int:idmovimiento>/', views.generar_liq_definitiva, name='generar_liq_definitiva'),
   # path('pdf/', GeneratePdf.as_view()),
    path('pdf/', views.generate_view, name='generate_view'),
    path('liquidacion_filtro/', views.liquidacion_filtro, name='liquidacion_filtro'),
    path('historico_movimientos/', views.historico_movimientos, name='historico_movimientos'),
    path('reporte_monto_motivo/', views.gastosxtipomovimiento, name='gastosxtipomovimiento'),
    path('informe_vacaciones/', views.informe_vacaciones, name='informe_vacaciones'),
    path('nomina_funcionarios/', views.nomina_funcionarios, name='nomina_funcionarios'),
    path('ajax/traer_departamentos/', views.traer_departamentos, name='traer_departamentos'),
    path('monto_objetodegasto/', views.monto_objetodegasto, name='monto_objetodegasto'),
    path('informe_altasbajas/', views.informe_altasbajas, name='informe_altasbajas'),
    path('print_liquidacion/<int:idliquidacion>/', views.print_liquidacion, name='print_liquidacion'),

]

sueldos/urls.py
import django.contrib
import table
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from liquidacion.views import *

urlpatterns = [
    path('', auth_views.login, name = 'login'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('liquidacion/', include('liquidacion.urls')),
    path('django_popup_view_field/', include('django_popup_view_field.urls', namespace="django_popup_view_field")),
    path('table/', include('table.urls')),
    path('home/', TemplateView.as_view(template_name='index.html'), name='home'),
]

handler404 = 'liquidacion.views.handler404'
handler500 = 'liquidacion.views.handler500'

liquidacion/models.py
import datetime
from django.db.models import Sum, Max, Q
from decimal import Decimal, ROUND_HALF_UP
from django.db import models, utils
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db.models.functions import Coalesce

from sueldos.settings import DATE_INPUT_FORMATS

ConstanteType_OPTIONS = (
    ('D', 'Debito'),
    ('C', 'Credito'),
)

Modalidad_OPTIONS = (
    ('M' , 'Mensual'),
    ('S' , 'Semestral'),
    ('O' , 'Otros'),
)

MES_OPTIONS = (
    ('Enero' , 'Enero'),
    ('Febrero' , 'Febrero'),
    ('Marzo' , 'Marzo'),
    ('Abril' , 'Abril'),
    ('Mayo' , 'Mayo'),
    ('Junio' , 'Junio'),
    ('Julio' , 'Julio'),
    ('Agosto' , 'Agosto'),
    ('Septiembre' , 'Septiembre'),
    ('Octubre' , 'Octubre'),
    ('Noviembre' , 'Noviembre'),
    ('Diciembre' , 'Diciembre'),

)

def validar_vacio(value):
    convertido = value.replace(" ", "")
    if not value:
        raise ValidationError(
            ('Debe completar este campo'),
        )
    return value


def validar_nombre(value):
    convertido = value.replace(" ", "")
    if convertido.isalpha() is False:
        raise ValidationError(
            ('%(value)s no es valido, favor ingrese un valor sin numeros ni simbolos'),
            params={'value': value},
        )

class Funcionario(models.Model):
    idFuncionario = models.AutoField(primary_key=True)
    cedula = models.CharField(max_length=50, default='')
    nombres = models.CharField(max_length=50, default='')
    apellidos = models.CharField(max_length=50, default='')
    fechanacimiento = models.DateField(verbose_name='Fecha de Nacimiento')
    direccion = models.CharField(max_length=100, default='')
    email = models.CharField(max_length=50, default='')
    telefono = models.CharField(max_length=50, default='')
    cantHijos = models.IntegerField(verbose_name='Cantidad de Hijos')
    #-----------------------------------Relationships-----------------------------------------#
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='fk_funcionario_usuario_fk')
    grado = models.ForeignKey('GradoUniversitario', on_delete=models.DO_NOTHING, related_name='fk_funcionario_grado' )
    estadocivil = models.ForeignKey('EstadoCivil', on_delete=models.DO_NOTHING, related_name='fk_funcionario_ecivil', verbose_name='Estado Civil')
    ciudadnacimiento = models.ForeignKey('Ciudad', on_delete=models.DO_NOTHING, related_name='fk_funcionario_ciudad', verbose_name='Lugar de Nacimiento')

    class Meta:
        ordering = ["apellidos"]
        verbose_name_plural = "Funcionarios"

    def __str__(self):
        return '%s %s' % (self.nombres, self.apellidos)


class Movimiento(models.Model):
    idmovimiento = models.AutoField(primary_key=True)
    codigo = models.CharField(max_length=20, default='', blank=True, null=True)
    tipo = models.ForeignKey('MovimientoType', on_delete=models.DO_NOTHING, related_name='fk_movimiento_tipo', blank=False)
    motivo = models.ForeignKey('MovimientoMotivo', on_delete=models.DO_NOTHING, related_name='fk_movimiento_motivo', blank=False)
    formapago = models.CharField(max_length=1,choices=Modalidad_OPTIONS, default='M', blank=False)
    fechainicio = models.DateField(blank=False)
    fechafin = models.DateField(blank=True, null=True)
    esPrimero = models.BooleanField(default=True)
    horaEntrada = models.TimeField(blank=True, null=True)
    horaSalida = models.TimeField(blank=True, null=True)
    tieneAguinaldo = models.BooleanField(default=False)
    tieneVacaciones = models.BooleanField(default=False)
    funcion = models.CharField(max_length=99, default='', validators=[validar_nombre], blank=False)
    familia = models.IntegerField(blank=True, null=True, default=1)
    #------------------------------------Relationships-----------------------------------------#
    ffinanciamiento = models.ForeignKey('FuenteFinanciamiento', on_delete=models.DO_NOTHING, default=1)
    funcionario = models.ForeignKey('Funcionario', on_delete=models.DO_NOTHING, related_name='fk_movimiento_funcionario')
    categoria_salarial = models.ForeignKey('CategoriaSalarial', on_delete=models.DO_NOTHING,
                                           related_name='fk_movimiento_categoriasalarial', blank=False)
    division = models.ForeignKey('Division', on_delete=models.DO_NOTHING, related_name='fk_movimiento_division', blank=False)
    og = models.ForeignKey('Objeto_De_Gasto', on_delete=models.DO_NOTHING, related_name='fk_movimiento_og')
    movimiento_padre = models.ForeignKey('self', on_delete=models.DO_NOTHING, blank=True, null=True)
    estado = models.ForeignKey('State', on_delete=models.DO_NOTHING, related_name='fk_movimiento_estado')


class Pago(models.Model):
    id = models.AutoField(primary_key=True)
    monto = models.IntegerField()
    pagado = models.BooleanField(default=False)
    # -----------------------------------Relationships-----------------------------------------#
    mes = models.ForeignKey('Mes', on_delete=models.DO_NOTHING, default=1)
    movimiento = models.ForeignKey('Movimiento', on_delete=models.CASCADE, related_name='fk_pago_movimiento')

    class Meta:
        verbose_name_plural = "Pagos"
        unique_together = (('mes', 'movimiento'),)


class FuenteFinanciamiento(models.Model):
    id = models.AutoField(primary_key=True)
    descripcion = models.CharField(max_length=50, default='', unique=True)
    numero = models.IntegerField()

    class Meta:
        ordering = ["descripcion"]
        verbose_name_plural = "Fuentes de Financiamiento"

    def __str__(self):
        return 'Fuente %s  - %s ' % (self.numero, self.descripcion)


class Objeto_De_Gasto(models.Model):
    id_og = models.AutoField(primary_key=True)
    concepto = models.CharField(max_length=100, default='', validators=[validar_nombre], unique=True)
    numero = models.IntegerField(unique=True)

    class Meta:
        ordering = ["numero"]
        verbose_name_plural = "Objetos de Gasto"

    def __str__(self):
        return '%s %s' % (self.numero, self.concepto)


class Departamento(models.Model):
    iddepartamento = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50, default='', validators=[validar_nombre], unique=True)
    # -----------------------------------Relationships-----------------------------------------#
    director = models.ForeignKey('Funcionario', on_delete=models.DO_NOTHING, related_name='fk_departamento_funcionario')

    class Meta:
        ordering = ["nombre"]
        verbose_name_plural = "Departamentos"

    def __str__(self):
        return '%s' % (self.nombre)


class Division(models.Model):
    iddivision = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50, default='', validators=[validar_nombre], unique=True)
    # -----------------------------------Relationships-----------------------------------------#
    jefe = models.ForeignKey('Funcionario', on_delete=models.DO_NOTHING, related_name='fk_division_funcionario')
    departamento = models.ForeignKey('Departamento', on_delete=models.DO_NOTHING, related_name='fk_division_departamento')

    class Meta:
        ordering = ["nombre"]
        verbose_name_plural = "Divisiones"

    def __str__(self):
        return '%s %s %s' % (self.nombre,' - ', self.departamento.nombre)


class Aguinaldo(models.Model):
    id = models.AutoField(primary_key=True)
    anho = models.IntegerField(default=datetime.datetime.today().year)
    cantidad_meses = models.DecimalField(default=0, max_digits=3, decimal_places=1, blank=True, null=True)
    acumulado = models.DecimalField(default=0, max_digits=12, decimal_places=2, blank=True, null=True)
    total = models.DecimalField(default=0, max_digits=12, decimal_places=2, blank=True, null=True)
    # -----------------------------------Relationships-----------------------------------------#
    movimiento = models.ForeignKey('Movimiento', on_delete=models.CASCADE, related_name='aguinaldo_movimiento')

    def calculo_acumulado(self, idliqhaber):
        liquidacion = Liquidacionhaber.objects.get(pk=idliqhaber)
        if self.movimiento.motivo.nombre != 'Contrato':
            print(liquidacion.subTotal)
            resultado = liquidacion.subTotal / Decimal(12)
            print(resultado)
        else:
            pago = liquidacion.pago
            resultado = pago.monto / 12
        return round(resultado)

    def calculo_total(self):
        resultado = self.acumulado
        return resultado


class Pais(models.Model):
    idpais = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50, default='', validators=[validar_nombre], unique=True)

    class Meta:
        ordering = ["nombre"]
        verbose_name_plural = "Paises"

    def __str__(self):
        return '%s ' % (self.nombre)


class Ciudad(models.Model):
    idciudad = models.AutoField(primary_key=True)
    nombreciudad = models.CharField(max_length=50, default='', validators=[validar_nombre], unique=True, verbose_name='Nombre de la Ciudad')
    # -----------------------------------Relationships-----------------------------------------#
    pais = models.ForeignKey('Pais', on_delete=models.CASCADE, related_name='fk_ciudad_pais')

    class Meta:
        ordering = ["nombreciudad"]
        verbose_name_plural = "Ciudades"

    def __str__(self):
        return '%s %s %s' % (self.nombreciudad, ' - ', self.pais)


class CategoriaSalarial(models.Model):
    id = models.AutoField(primary_key=True)
    codigo = models.CharField(max_length=20, default='', unique=True)
    tipo = models.CharField(max_length=30, default='')
    cargo = models.CharField(max_length=50, default='', validators=[validar_nombre])
    asignacion = models.IntegerField()

    class Meta:
        ordering = ["codigo"]
        verbose_name_plural = "Categorias Salariales"

    def __str__(self):
        return '%s ' % self.codigo


class EstadoCivil(models.Model):

templates/proceso/documento_form.html
{% load l10n %}
<div class="modal-dialog">
    <div class="modal-content" style="background-color: #b9bbbe" id="documento_modal">
        <div class="modal-header text-center">
            <h4 class="modal-title w-100 font-weight-bold">Documento Respaldatorio</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div id="modal-body" class="modal-body">
            {% if documento %}
            <form class="well" role="form" action="{% url 'liquidacion:ver_documento' documento.movimiento.pk documento.pk %}" method="post">
            {% else %}
            <form role="form" action="{% url 'liquidacion:nuevo_documento' movimiento.pk %}" method="post">
            {% endif %}
            {% csrf_token %}
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label for="tipodoc">Tipo de Documento:</label>
                                {% if documento %}
                                    <input type="text" id="tipo" class="form-control"
                                           value="{{ documento.tipo }}" disabled/>
                                {% else %}
                                    {{ form.tipo }}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label for="codigo">Codigo:</label>
                                {% if documento %}
                                    <input type="text" id="codigo" class="form-control"
                                           value="{{ documento.codigo }}" disabled/>
                                {% else %}
                                    {{ form.codigo }}
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label for="fechaemision">Fecha de Emision:</label>
                                <div class="input-group">
                                {% if documento %}
                                    <input type="date" id="id_fechainicio" name="fechainicio" class="form-control"
                                               value="{{ documento.fechaemision|unlocalize }}" placeholder="{{ documento.fechaemision|unlocalize }}" disabled>
                                    <span class="input-group-btn">
                                        <button class="btn btn-secondary" type="button" disabled>
                                            <i class="fa fa-calendar" aria-hidden="true"></i>
                                        </button>
                                    </span>
                                {% else %}
                                    <input type="date" id="id_fechaemision" name="fechaemision" class="form-control">
                                    <span class="input-group-btn">
                                        <button class="btn btn-secondary" type="button" disabled>
                                            <i class="fa fa-calendar" aria-hidden="true"></i>
                                        </button>
                                    </span>
                                {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label for="autoridadfirmante">Autoridad Firmante:</label>
                                {% if documento %}
                                    <input type="text" id="autoridadfirmante" class="form-control"
                                           value="{{ documento.autoridadfirmante }}" disabled/>
                                {% else %}
                                    {{ form.autoridadfirmante }}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label for="quienfirma">Firmado por:</label>
                                <div class="input-group">
                                {% if documento %}
                                    <input type="text" id="quienfirma" class="form-control"
                                           value="{{ documento.quienfirma }}" disabled/>
                                {% else %}
                                    {{ form.quienfirma }}
                                {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        {% if not documento %}
                <div class="modal-footer">
                    <div class="col-lg-12 text-right">
                        <input type="submit" class="btn btn-primary" name="submit" value="Guardar">
                    </div>
                </div>
        {% endif %}
        </form>
    </div>
    </div>
</div>

templates/proceso/opciones_proceso.html
<div class="modal-dialog">
    <div class="modal-content" id="opciones_proceso_modal" style="background-color: #b9bbbe">
      <div class="modal-header">
          <h4>Seleccione una opción</h4>
          <button type="button" class="close" data-dismiss="modal">×</button>
      </div>
        <div class="modal-body">
            <div class="panel panel-default">
                <div class="panel-body">
                    <ul class="list-group" style="background-color: #b9bbbe">
                        <li class="list-group-item" style="background-color: #b9bbbe">
                          <a class="btn btn-light opciones" href="{% url 'liquidacion:buscar_funcionario' %}"
                             id="" style="width: 100%;">Nuevo cargo de Funcionario</a>
                        </li>
                        <li class="list-group-item" style="background-color: #b9bbbe">
                          <a class="btn btn-light opciones" href="{% url 'liquidacion:buscar_movimiento' %}"
                             id="" style="width: 100%;">Ascenso o modificación de funciones</a>
                        </li>
                        <li class="list-group-item" style="background-color: #b9bbbe">
                          <a class="btn btn-light opciones" href="{% url 'liquidacion:parametros_liq_mensual' %}"
                             id="" style="width: 100%;">Generación de Liquidacion Salarial Mensual</a>
                        </li>
                        <li class="list-group-item" style="background-color: #b9bbbe">
                          <a class="btn btn-light opciones" href="{% url 'liquidacion:param_liq_definitiva' %}"
                             id="" style="width: 100%;">Generacion de Liquidacion por Baja de Funcionario</a>
                        </li>
                        <li class="list-group-item" style="background-color: #b9bbbe">
                          <a class="btn btn-light opciones" href="{% url 'liquidacion:liquidaciones_periodo' %}"
                             id="" style="width: 100%;">Consulta de Liquidaciones Pendientes del periodo </a>
                        </li>
                         <li class="list-group-item" style="background-color: #b9bbbe">
                          <a class="btn btn-light opciones" href="{% url 'liquidacion:confirmadas_periodo' %}"
                             id="" style="width: 100%;">Consulta de Liquidaciones Confirmadas del periodo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
            <div class="modal-footer">

            </div>
    </div>
</div>

templates/proceso/seleccion_movimiento_funcionario.html
{% extends 'index.html' %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}

{% block navbar %}
    <li class="nav-item">
    <a id="" data-toggle="modal" data-target="#help_modal" class="nav-link text-center">
        <i class="fa fa-question-circle"></i> Ayuda</a>
    </li>
{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb " Seleccion de Movimiento de Funcionario "  'liquidacion:index' %}
{% endblock %}

{% block content %}
{% render_breadcrumbs %}

<div class="col-12 col-sm-10 recuadro">

<div class="row">
    <div class="col-12">
        <div class="col-12 d-flex align-self-start">
            <h5><strong>Seleccion de movimiento para Ascenso o Modificacion de funciones</strong></h5>
        </div>
    </div>
</div>

<hr>

<div class="row">
    <div class="col-12">
    <label for="funcionario" class="explicativo"><strong>Ingrese el numero de cedula de identidad del funcionario</strong></label>
    <form method="get" class="form-inline">
            <div class="input-group">
                {{ form.funcionario }}
            <span class="input-group-append">
                <button type="submit" class="btn btn-light opciones" name="q" value="true"
                        formaction="{% url 'liquidacion:buscar_movimiento' %}" style="display:inline-block;">
                   <i class="fa fa-search"></i>
                </button>
             </span>
    </div>
    </form>
    </div>
</div>

{% if funcionarios %}
<div class="row separador mt-2"></div>
    <div class="row separador_fila">
        <div class="col-lg-12">
            <table class="table table-hover table-striped table-sm">
                <thead class="thead-light">
                    <tr>
                        <th class="text-center">Nombres</th>
                        <th class="text-center">Apellidos</th>
                        <th class="text-center">Tipo de movimiento</th>
                        <th class="text-center">Categoria Salarial</th>
                        <th class="text-center">Seleccionar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for movimiento in funcionarios %}
                        <tr class='clickable-row'>
                            <td class="text-center">{{ movimiento.funcionario.nombres }}</td>
                            <td class="text-center">{{ movimiento.funcionario.apellidos }}</td>
                            <td class="text-center">{{ movimiento.motivo.nombre }}</td>
                            <td class="text-center">{{ movimiento.categoria_salarial.codigo }}</td>
                            <td class="text-center">
                                <button class="btn btn-secondary" type="button"
                                   name="go" value="Ir" onclick="location.href=('{% url 'liquidacion:modificar_movimiento' movimiento.pk %}')">
                                <i class="fa fa-edit" aria-hidden="true"></i></button>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endif %}

<div id="help_modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" style="background-color: #b9bbbe">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold" style="color: #007bff">Información de ayuda al usuario</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>En esta pantalla usted podrá buscar los cargos activos de un funcionario
                al cual desea asignarle un ascenso o modificacion de funciones en la institución,
                    para el efecto ingrese el número de
                documento de identidad del mismo y presione el ícono de búsqueda
                    <button class="btn btn-light" style="background-color: #3B598D;color: white;">
                        <i class="fa fa-search"></i></button>.</p>
                <p>Una vez que aparezcan en pantalla los cargos activos del funcionario, seleccione la opción
                    deseada presionando el botón
                    <button class="btn btn-secondary btn-edit" type="button" onclick=""><i class="fa fa-edit" aria-hidden="true"></i></button>
                    ubicado a la derecha de la fila.
                </p>
            </div>
            <div id="modal-body" class="modal-footer">
                <button type="button" class="btn btn-primary btn-block" data-dismiss="modal">Entendido</button>
            </div>
        </div>
    </div>
</div>

</div>


<footer>
    <script>
        $(document).ready(function () {

        });

        $('#xx_btn').click(function(e) {
            e.preventDefault();
            $.ajax({
                url: '{% url 'liquidacion:get_movimientos' %}',
                type : 'GET',
                dataType: 'json',
                data: {
                    idfuncionario: $("#funcionario_btn").val()
                },
                success: function (response) {
                    $('#tablamovimientos').show();
                    var tabla_movimientos = $('#tabla_movimientos');
                    $.each(response, function (key, value) {
                        var idpadre = value.idmovimiento;
                        var link = "{% url 'liquidacion:modificar_movimiento' 0 %}";
                        link = link.replace(0, idpadre);

                        tabla_movimientos.append('<tr>' + '<td>' + value.motivo + '</td>' + '<td>'
                            + value.tipo + '</td>' + '<td>' + value.categoria_salarial + '</td>'
                            +'<td>'
                            +'<button id="movimiento_btn" class="btn btn-secondary btn-edit" onclick="location.href='+"'" + link +"'" +'">'
                            +'<i class="fa fa-check-square-o"></i>' +
                            +'</button>' + '</td>' + '</tr>'
                            )
                    });
                },
                error: function (data) {
                    console.log(data)
                }
            })
        });

    </script>
</footer>

{% endblock %}