liquidacion/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.views.i18n import JavaScriptCatalog

from liquidacion.views import *
from . import views

app_name = 'liquidacion'

urlpatterns = [
    #path('accounts/login/', 'django.contrib.auth.views.login', name='login'),
    #path('accounts/logout/', 'django.contrib.auth.views.logout', name='logout'),
    path('home/', views.index, name='index'),
    path('opciones_proceso', views.opciones_proceso, name='opciones_proceso'),
    path('opciones_vacaciones', views.opciones_vacaciones, name='opciones_vacaciones'),
    path('opciones_reportes', views.opciones_reportes, name='opciones_reportes'),
    path('funcionario/<int:idfuncionario>/movimiento/nuevo/', views.movimiento_vista, name='nuevo_movimiento'),
    path('movimiento_padre/<int:idpadre>/', views.movimiento_vista, name='modificar_movimiento'),
    path('movimiento/<int:idmovimiento>', views.movimiento_vista, name='editar_movimiento'),
    path('buscar_funcionario', views.busqueda_funcionarios, name='buscar_funcionario'),
    path('buscar_movimiento', views.busqueda_movimiento_funcionario, name='buscar_movimiento'),
    path('get_movimientos', views.get_movimientos, name='get_movimientos'),
    path('movimiento/<int:idmovimiento>/documento/nuevo/', views.documento_vista, name='nuevo_documento'),
    path('movimiento/<int:idmovimiento>/documento/<int:iddocumento>', views.documento_vista, name='ver_documento'),
    path('movimiento/<int:idmovimiento>/constante/nuevo/', views.constante_vista, name='nueva_constante'),
    path('movimiento/<int:idmovimiento>/constante/<int:idconstante>', views.constante_vista, name='borrar_constante'),
    path('categoriasalarial-list', CategoriaSalarialList.as_view(), name='categoriasalarial-list'),
    path('objetodegasto/add/', ObjetoDeGastoCreate.as_view(), name='objetodegasto-add'),
    path('tipomovimiento/add/', TipoMovimientoCreate.as_view(), name='tipomovimiento-add'),
    path('movimientomotivo/add/', MovimientoMotivoCreate.as_view(), name='movimientomotivo-add'),
    path('success_page/<int:idmovimiento>/', views.success_page, name='success_page'),
    path('movimiento_resumen/<int:idmovimiento>/', views.mostrar_movimiento_resumen, name='movimiento_resumen'),
    path('ajax/traer_tipomovimientos/', views.traer_tipomovimientos, name='traer_tipomovimientos'),
    path('ajax/traer_og/', views.traer_og, name='traer_og'),
    path('ajax/traer_variables/', views.traer_variables, name='traer_variables'),
    path('ajax/traer_constantes/', views.traer_constantes, name='traer_constantes'),
    path('ajax/traer_motivomovimientos/', views.traer_motivomovimientos, name='traer_motivomovimientos'),
    path('buscarmovimientofuncionario/', views.buscar_movimientos_funcionario, name='buscar_movimientos_funcionario'),
    path('movimiento/<int:idmovimiento>/pago/nuevo/', views.pago_vista, name='nuevo_pago'),
    path('liquidacionm/seleccion/', views.parametros_liq_mensual, name='parametros_liq_mensual'),
    path('ajax/traer_departamentos/', views.traer_departamentos, name='traer_departamentos'),
    path('ajax/traer_funcionarios/', views.traer_funcionarios, name='traer_funcionarios'),
    path('liqpendientes/dpto/<int:iddpto>/mes/<int:mes>/anho/<int:anho>/', views.liq_pendientes_list, name='liq_pendientes_list'),
    path('editar_liquidacion/<int:idliquidacion>/', views.vista_liq_mensual, name='editar_liquidacion'),
    path('liquidacion_haber/<int:idliquidacionhaber>/', views.vista_liquidacionhaber, name='editar_liquidacionhaber'),
    path('liquidacionhaber/<int:idliquidacionhaber>/detalle/nuevo/', views.vista_detalleliquidacion, name='detalleliquidacion-add'),
    path('liquidacionhaber/<int:idliquidacionhaber>/detalle/<int:iddetalleliq>', views.vista_detalleliquidacion,
         name='detalleliquidacion-edit'),
    path('detalle/<int:pk>/delete/', views.delete_detalleliquidacion, name='detalleliquidacion-delete'),
    path('carga_vacaciones/', views.vacaciones_form, name='cargar_vacaciones'),
    path('liquidacion/pendientes/', views.liq_pendientes_filtro, name='liq_pendientes_filtro'),
    path('liqpendientes/funcionario/<int:funcionario>/mes/<int:mes>/', views.liq_funcionarios_list, name='liq_funcionarios_list'),
    path('ajax/traer_mes/', views.traer_mes, name='traer_mes'),
    path('liquidaciones/periodo/', views.liquidaciones_periodo, name='liquidaciones_periodo'),
    path('confirmar_liquidaciones/', views.confirmar_liquidaciones, name='confirmar_liquidaciones'),
    path('consulta_vacaciones/', views.consulta_vacaciones, name='consulta_vacaciones'),
    path('liquidaciones/confirmadas/periodo/', views.confirmadas_periodo, name='confirmadas_periodo'),
    path('liquidaciond/seleccion/', views.param_liq_definitiva, name='param_liq_definitiva'),
    path('liquidacion_baja/movimiento/<int:idmovimiento>/', views.generar_liq_definitiva, name='generar_liq_definitiva'),
   # path('pdf/', GeneratePdf.as_view()),
    path('pdf/', views.generate_view, name='generate_view'),
    path('liquidacion_filtro/', views.liquidacion_filtro, name='liquidacion_filtro'),
    path('historico_movimientos/', views.historico_movimientos, name='historico_movimientos'),
    path('reporte_monto_motivo/', views.gastosxtipomovimiento, name='gastosxtipomovimiento'),
    path('informe_vacaciones/', views.informe_vacaciones, name='informe_vacaciones'),
    path('nomina_funcionarios/', views.nomina_funcionarios, name='nomina_funcionarios'),
    path('ajax/traer_departamentos/', views.traer_departamentos, name='traer_departamentos'),
    path('monto_objetodegasto/', views.monto_objetodegasto, name='monto_objetodegasto'),
    path('informe_altasbajas/', views.informe_altasbajas, name='informe_altasbajas'),
    path('print_liquidacion/<int:idliquidacion>/', views.print_liquidacion, name='print_liquidacion'),

]

sueldos/urls.py
import django.contrib
import table
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from liquidacion.views import *

urlpatterns = [
    path('', auth_views.login, name = 'login'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('liquidacion/', include('liquidacion.urls')),
    path('django_popup_view_field/', include('django_popup_view_field.urls', namespace="django_popup_view_field")),
    path('table/', include('table.urls')),
    path('home/', TemplateView.as_view(template_name='index.html'), name='home'),
]

handler404 = 'liquidacion.views.handler404'
handler500 = 'liquidacion.views.handler500'

liquidacion/forms.py
from django import forms
from django.contrib import admin
#from django.forms import *
from django.forms import ModelForm, NumberInput, IntegerField
from django.forms.widgets import SelectDateWidget, DateInput
from django.forms.fields import DateField
from liquidacion.models import *
from sueldos.settings import DATE_INPUT_FORMATS
from django.contrib.admin.widgets import AdminDateWidget
from django.contrib.postgres.forms.ranges import DateRangeField, RangeWidget
from django.forms.widgets import TimeInput

MES_OPTIONS = (
    (0 , 'Todos'),
    (1 , 'Enero'),
    (2 , 'Febrero'),
    (3 , 'Marzo'),
    (4 , 'Abril'),
    (5 , 'Mayo'),
    (6 , 'Junio'),
    (7 , 'Julio'),
    (8 , 'Agosto'),
    (9 , 'Septiembre'),
    (10 , 'Octubre'),
    (11 , 'Noviembre'),
    (12 , 'Diciembre'),
)

MES2_OPTIONS = (
    (1 , 'Enero'),
    (2 , 'Febrero'),
    (3 , 'Marzo'),
    (4 , 'Abril'),
    (5 , 'Mayo'),
    (6 , 'Junio'),
    (7 , 'Julio'),
    (8 , 'Agosto'),
    (9 , 'Septiembre'),
    (10 , 'Octubre'),
    (11 , 'Noviembre'),
    (12 , 'Diciembre'),
)

MOTIVO_OPTIONS = (
    ('Contrato', 'Contrato'),
    ('Permanente' , 'Permanente'),
)

TIPO_OPTIONS = (
    ('Alta', 'Alta'),
    ('Baja' , 'Baja'),
)


class FilroTipoMovimientoForm(forms.Form):

    desde = forms.DateTimeField(label='Desde', required=True,
                          widget=forms.TextInput(attrs={'class': 'form-control datepicker',
                                                  'id': 'fec_ini',}))

    hasta = forms.DateTimeField(label='Hasta', required=True,
                          widget=forms.TextInput(attrs={'class': 'form-control datepicker',
                                                  'id': 'fec_fin',}))

    tipo = forms.ChoiceField(label='Tipo de Movimiento', required=True, choices=TIPO_OPTIONS, widget=forms.Select(attrs={'class': 'form-control'}))


class FiltroMesForm(forms.Form):

    mes = forms.ChoiceField(label='Mes', required=True, choices=MES_OPTIONS, widget=forms.Select(attrs={'class': 'form-control',
                                                                                          'name': 'mes',
                                                                                          'id': 'mes-select',
                                                                                          }))


class FiltroDepartamentoForm(forms.Form):

    departamento = IntegerField(label='Departamento', required=True, widget=forms.Select(attrs={'class': 'form-control',
                                                                                          'name': 'departamento-select',
                                                                                          'id': 'departamento-select',
                                                                                          }))


class FiltroGastosForm(forms.Form):

    motivo = forms.ChoiceField(label='Tipo de cargo', required=True, choices=MOTIVO_OPTIONS, widget=forms.Select(attrs={'class': 'form-control',
                                                                                          'name': 'motivo',
                                                                                          'id': 'motivo-select',
                                                                                          }))

    anho = forms.IntegerField(label='Año', required=True, widget=forms.NumberInput(attrs={'class': 'form-control',
                                                                                          'name': 'anho',
                                                                                          }))


class LiquidacionDefinitivaForm(forms.Form):

    funcionario = IntegerField(label='Nro. de Documento de Identidad', required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'placeholder' : "Ingrese el número de documento",}))

class VacacionesFuncionarioForm(forms.Form):

    funcionario = IntegerField(label='Nro. de Documento de Identidad', required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'placeholder' : "Ingrese el numero de documento de identidad"}))


class LiqPendientesForm(forms.Form):

    funcionario = forms.CharField(label='Funcionario', required=True, widget=forms.TextInput(attrs={'class': 'form-control',
                                                              'name': 'funcionario',
                                                              }))

    mes = forms.ChoiceField(label='Mes', required=True, choices=MES2_OPTIONS, widget=forms.Select(attrs={'class': 'form-control',
                                                                                          'name': 'mes',
                                                                                          'id': 'mes-select',
                                                                                          }))

    anho = forms.IntegerField(label='Año', required=True, widget=forms.NumberInput(attrs={'class': 'form-control',
                                                                                          'name': 'anho',
                                                                                          }))

class VacacionesusadasForm(forms.ModelForm):
    class Meta:
        model = Vacacionesusadas
        exclude = ['vacaciones']
        widgets = {
            'diasusados': forms.NumberInput(attrs={
                'class': 'form-control',
            }),
        }


class DetalleLiquidacionForm(forms.ModelForm):
    class Meta:
        model = DetalleLiquidacion
        exclude = ['liquidacion','total', 'salario_proporcional', 'pago']
        widgets = {
            'variable': forms.Select(attrs={
                'class': 'form-control',
            }),
            'parametro': forms.Select(attrs={
                'class': 'form-control',
            }),
            'cantidad': forms.NumberInput(attrs={
                'class': 'form-control',
            }),
            'monto': forms.NumberInput(attrs={
                'class': 'form-control',
            }),
        }


class LiquidacionhaberForm(forms.ModelForm):
    class Meta:
        model = Liquidacionhaber
        fields = '__all__'


class LiqMensualForm(forms.ModelForm):
    class Meta:
        model = Liquidacion
        exclude = ['ultimamodificacion' ,'propietario', 'tipo', 'haberes']
        widgets = {
            'vacaciones_usadas': forms.NumberInput(attrs={
                'class': 'form-control',
                'size' : "30",
            }),
            'motivo': forms.Select(attrs={
                'class': 'form-control',
            }),
        }


class PreLiqMensualForm(forms.Form):

    desde = forms.DateTimeField(label='Desde', required=True,
                          widget=forms.TextInput(attrs={'class': 'form-control datepicker',
                                                  'id': 'fec_ini',}))

    hasta = forms.DateTimeField(label='Hasta', required=True,
                          widget=forms.TextInput(attrs={'class': 'form-control datepicker',
                                                  'id': 'fec_fin',}))

    departamento = forms.IntegerField(label='Departamento', required=True, widget=forms.Select(attrs={'class': 'form-control',
                                                                                          'name': 'departamento',
                                                                                          'id': 'departamento-select',
                                                                                          }))

class FuncionarioForm(forms.ModelForm):
    class Meta:
        model = Funcionario
        fields = '__all__'
        widgets = {
            'usuario': forms.Select(attrs={
                'class': 'form-control',
            }),
        }


class MovimientoForm(forms.ModelForm):
    class Meta:
        model = Movimiento
        exclude = ['movimiento_padre','funcionario','estado','esPrimero', 'familia']
        widgets = {
            'codigo': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'categoria_salarial': forms.TextInput(attrs={
                'type': 'hidden',
                'class': 'form-control'
            }),
            'og': forms.Select(attrs={
                'class': 'form-control'
            }),
            'tipo': forms.Select(attrs={
                'class': 'form-control'
            }),
            'motivo': forms.Select(attrs={
                'class': 'form-control'
            }),
            'formapago': forms.Select(attrs={
                'class': 'form-control'
            }),
            'ffinanciamiento': forms.Select(attrs={
                'class': 'form-control'
            }),
            'division': forms.Select(attrs={
                'class': 'form-control'
            }),
            'funcion': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'fechainicio': forms.DateInput(attrs={
                'type': 'date',
                'class': 'form-control',
            }),
            'fechafin': forms.DateInput(attrs={
                'type' : 'date',
                'class': 'form-control',
                'readonly': True
            }),
            'horaEntrada': forms.TimeInput(attrs={
                'class': 'form-control',
                'readonly': True
            }),
            'horaSalida': forms.TimeInput(attrs={
                'class': 'form-control',
                'readonly': True
            }),
            'tieneAguinaldo': forms.CheckboxInput(attrs={
                'class': 'form-control'
            }),
            'tieneVacaciones': forms.CheckboxInput(attrs={
                'class': 'form-control'
            }),

templates/reportes/filtro_altasybajas.html
{% extends "index.html" %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
{% load l10n %}

{% block navbar %}
    <li class="nav-item">
    <a id="" data-toggle="modal" data-target="#help_modal" class="nav-link text-center">
        <i class="fa fa-question-circle"></i> Ayuda</a>
    </li>
{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb " Filtro para reporte de altas y bajas " 'liquidacion:informe_altasbajas' %}
{% endblock %}

{% block head %}
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
{% endblock %}

{% block content %}
{% render_breadcrumbs %}

    <div class="col-12 col-sm-10 recuadro">
        <form method="POST">
        {% csrf_token %}
        <div class="row">
        <div class="col-12">
            <div class="col-12 d-flex align-self-start">
                <h5>Reporte de Altas y Bajas</h5>
            </div>
        </div>
        </div>
        <hr>
        {% if advertencia %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ advertencia }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif %}
        <div class="row">
        <div class="col-lg-10">
            {% for message in messages %}
                {% if message.error %}
                <div class="alert alert-danger">{{ message }}
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                </div>
                {% endif %}
                    <div class="alert alert-warning">{{ message }}
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    </div>
            {% endfor %}
        </div>
        </div>

        <div class="row">
        <div class="col-md-6">
        <div class="form-group">
            <label for="desde"><strong>Desde</strong></label>
                <div class="input-group">
                    {% if form.desde.errors %}
                    <ol>
                    {% for error in form.desde.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                    {% endfor %}
                    </ol>
                    {% endif %}
                    <input type="date" id="id_desde" name="desde" class="form-control">
                    <span class="input-group-btn">
                        <button class="btn btn-secondary" type="button" disabled>
                            <i class="fa fa-calendar" aria-hidden="true"></i>
                        </button>
                    </span>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="hasta"><strong>Hasta</strong></label>
                    <div class="input-group">
                    {% if form.hasta.errors %}
                    <ol>
                    {% for error in form.hasta.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                    {% endfor %}
                    </ol>
                    {% endif %}
                    <input type="date" id="id_hasta" name="hasta" class="form-control">
                    <span class="input-group-btn">
                        <button class="btn btn-secondary" type="button" disabled>
                            <i class="fa fa-calendar" aria-hidden="true"></i>
                        </button>
                    </span>
                    </div>
                </div>
        </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="tipo"><strong>Tipo de movimiento</strong></label>
                    <div class="input-group">
                        {{ form.tipo }}
                    </div>
                </div>
            </div>

            <div class="col-md-4 align-self-end pb-3">
                <button type="submit" class="btn btn-light opciones" name="q" value="true"
                        formaction="{% url 'liquidacion:informe_altasbajas' %}">
                    Consultar
                </button>
            </div>
        </div>

        {% if form.errors %}
        <div class="row mt-0">
            <div class="col-md-4">
                <strong style="color:red">{{ form.cedula.errors.as_text }}</strong>
            </div>

            <div class="col-md-4">
                <strong style="color:red">{{ form.nombres.errors.as_text }}</strong>
            </div>

            <div class="col-md-4">
                <strong style="color:red">{{ form.apellidos.errors.as_text }}</strong>
            </div>
        </div>
        {% endif %}

        </form>

        <div class="row mt-3 mb-3"></div>

        {% if sin_datos %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ sin_datos }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        {% endif %}
        </div>

<div id="help_modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" style="background-color: #b9bbbe">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold" style="color: #007bff">Información de ayuda al usuario</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>En esta pantalla usted podrá generar un informe de Altas o Bajas de funcionarios correspondiente a un periodo
                    de tiempo determinado.</p>
                <p>Para generar el informe ingrese la fecha de inicio del periodo del informe y la fecha limite de fin
                    , en la opcion <strong>Tipo de movimiento</strong> seleccione <strong>Alta</strong> o
                    <strong>Baja</strong> según los datos que desee ver en el informe y luego presione el botón
                    <button class="btn btn-light" style="background-color: #3B598D;color: white;">
                        Consultar
                    </button>.</p>
            </div>
            <div id="modal-body" class="modal-footer">
                <button type="button" class="btn btn-primary btn-block" data-dismiss="modal">Entendido</button>
            </div>
        </div>
    </div>
</div>


<footer>
    <script>
        function cargarFec() {
            var fecha_inicio = document.getElementById("fec-ini").value;
            var hora_inicio = document.getElementById("hora-ini").value;
            var min_ini = document.getElementById("min-ini").value;
            var fecha_fin = document.getElementById("fec-fin").value;
            var hora_fin = document.getElementById("hora-fin").value;
            var min_fin = document.getElementById("min-fin").value;
            document.getElementById("fechainicio").value = fecha_inicio + " " + hora_inicio + ":" + min_ini;
            document.getElementById("fechafin").value = fecha_fin + " " + hora_fin + ":" + min_fin;
        }
    </script>
    <script>
        $(function () {
            $(".datepicker").datepicker({dateFormat: "yy-mm-dd"});
        });
    </script>
    <script type="text/javascript">
        {% if lista %}
            $(document).ready(function () {
                $("#success_modal").modal('show');
            });
        {% endif %}
    </script>
    <script>
            $(document).ready(function (event) {
                var departamento_select = $('#departamento-select');
                $.ajax({
                    url: '{% url 'liquidacion:traer_departamentos' %}',
                    dataType: 'json',
                    data: {},
                    success: function (data) {
                        if ($.trim(data)) {
                            departamento_select.empty().append('<option value=' + 0 + ' selected >' + '------' + '</option>');
                            $.each(data, function (key, value) {
                                departamento_select.append('<option value=' + value.id + '>' + value.value + '</option>')
                            });
                        } else {
                            departamento_select.empty().append('<option value=' + 0 + ' selected>' + '------' + '</option>');
                        }
                    },
                    error: function (data) {
                        departamento_select.empty().append('<option value=' + 0 + ' selected disabled="true">' + 'No hay datos' + '</option>');
                    }
                })
            });
        </script>
        <script>
            $('#departamento-select').on('change', function (e) {
                var opcion_sel = $('#departamento-select').find('option:selected');
                var departamento_select = $('#departamento-select');
                $.ajax({
                    url: '{% url 'liquidacion:traer_funcionarios' %}',
                    dataType: 'json',
                    data: {
                        iddepartamento: opcion_sel.val()
                    },
                    success: function (data) {
                        console.log(data)
                    },
                    error: function (data) {
                    }
                })
            });
        </script>
</footer>

{% endblock %}

templates/reportes/opciones_reportes.html
<div class="modal-dialog">
    <div class="modal-content" id="opciones_reporte_modal" style="background-color: #b9bbbe">
      <div class="modal-header">
          <h4>Lista de Informes y Reportes</h4>
        <button type="button" class="close" data-dismiss="modal">×</button>
      </div>
        <div class="modal-body">
            <div class="panel panel-default">
                <div class="panel-body">
                    <ul class="list-group" style="background-color: #b9bbbe">
                        <li class="list-group-item" style="background-color: #b9bbbe">
                          <a class="btn btn-light opciones" href="{% url 'liquidacion:buscar_movimientos_funcionario' %}"
                             id="" style="width: 100%">Consulta de cargos activos</a>
                        </li>
                        <li class="list-group-item" style="background-color: #b9bbbe">
                          <a class="btn btn-light opciones" href="{% url 'liquidacion:liquidacion_filtro' %}"
                             id="" style="width: 100%">Imprimir liquidacion salarial</a>
                        </li>
                        <li class="list-group-item" style="background-color: #b9bbbe">
                          <a class="btn btn-light opciones" href="{% url 'liquidacion:historico_movimientos' %}"
                             id="" style="width: 100%">Informe histórico de cargos de funcionario</a>
                        </li>
                        <li class="list-group-item" style="background-color: #b9bbbe">
                          <a class="btn btn-light opciones" href="{% url 'liquidacion:gastosxtipomovimiento' %}"
                             id="" style="width: 100%">Reporte de monto gastado por tipo de cargo</a>
                        </li>
                        <li class="list-group-item" style="background-color: #b9bbbe">
                          <a class="btn btn-light opciones" href="{% url 'liquidacion:informe_vacaciones' %}"
                             id="" style="width: 100%">Resumen de vacaciones por funcionario</a>
                        </li>
                         <li class="list-group-item" style="background-color: #b9bbbe">
                          <a class="btn btn-light opciones" href="{% url 'liquidacion:nomina_funcionarios' %}"
                             id="" style="width: 100%">Nómina de funcionarios por departamento</a>
                        </li>
                        <li class="list-group-item" style="background-color: #b9bbbe">
                          <a class="btn btn-light opciones" href="{% url 'liquidacion:monto_objetodegasto' %}"
                             id="" style="width: 100%">Resumen de importe utilizado por Objeto de gasto</a>
                        </li>
                        <li class="list-group-item" style="background-color: #b9bbbe">
                          <a class="btn btn-light opciones" href="{% url 'liquidacion:informe_altasbajas' %}"
                             id="" style="width: 100%">Informe de Altas y Bajas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
            <div class="modal-footer">

            </div>
    </div>
</div>