liquidacion/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.views.i18n import JavaScriptCatalog

from liquidacion.views import *
from . import views

app_name = 'liquidacion'

urlpatterns = [
    #path('accounts/login/', 'django.contrib.auth.views.login', name='login'),
    #path('accounts/logout/', 'django.contrib.auth.views.logout', name='logout'),
    path('home/', views.index, name='index'),
    path('opciones_proceso', views.opciones_proceso, name='opciones_proceso'),
    path('opciones_vacaciones', views.opciones_vacaciones, name='opciones_vacaciones'),
    path('opciones_reportes', views.opciones_reportes, name='opciones_reportes'),
    path('funcionario/<int:idfuncionario>/movimiento/nuevo/', views.movimiento_vista, name='nuevo_movimiento'),
    path('movimiento_padre/<int:idpadre>/', views.movimiento_vista, name='modificar_movimiento'),
    path('movimiento/<int:idmovimiento>', views.movimiento_vista, name='editar_movimiento'),
    path('buscar_funcionario', views.busqueda_funcionarios, name='buscar_funcionario'),
    path('buscar_movimiento', views.busqueda_movimiento_funcionario, name='buscar_movimiento'),
    path('get_movimientos', views.get_movimientos, name='get_movimientos'),
    path('movimiento/<int:idmovimiento>/documento/nuevo/', views.documento_vista, name='nuevo_documento'),
    path('movimiento/<int:idmovimiento>/documento/<int:iddocumento>', views.documento_vista, name='ver_documento'),
    path('movimiento/<int:idmovimiento>/constante/nuevo/', views.constante_vista, name='nueva_constante'),
    path('movimiento/<int:idmovimiento>/constante/<int:idconstante>', views.constante_vista, name='borrar_constante'),
    path('categoriasalarial-list', CategoriaSalarialList.as_view(), name='categoriasalarial-list'),
    path('objetodegasto/add/', ObjetoDeGastoCreate.as_view(), name='objetodegasto-add'),
    path('tipomovimiento/add/', TipoMovimientoCreate.as_view(), name='tipomovimiento-add'),
    path('movimientomotivo/add/', MovimientoMotivoCreate.as_view(), name='movimientomotivo-add'),
    path('success_page/<int:idmovimiento>/', views.success_page, name='success_page'),
    path('movimiento_resumen/<int:idmovimiento>/', views.mostrar_movimiento_resumen, name='movimiento_resumen'),
    path('ajax/traer_tipomovimientos/', views.traer_tipomovimientos, name='traer_tipomovimientos'),
    path('ajax/traer_og/', views.traer_og, name='traer_og'),
    path('ajax/traer_variables/', views.traer_variables, name='traer_variables'),
    path('ajax/traer_constantes/', views.traer_constantes, name='traer_constantes'),
    path('ajax/traer_motivomovimientos/', views.traer_motivomovimientos, name='traer_motivomovimientos'),
    path('buscarmovimientofuncionario/', views.buscar_movimientos_funcionario, name='buscar_movimientos_funcionario'),
    path('movimiento/<int:idmovimiento>/pago/nuevo/', views.pago_vista, name='nuevo_pago'),
    path('liquidacionm/seleccion/', views.parametros_liq_mensual, name='parametros_liq_mensual'),
    path('ajax/traer_departamentos/', views.traer_departamentos, name='traer_departamentos'),
    path('ajax/traer_funcionarios/', views.traer_funcionarios, name='traer_funcionarios'),
    path('liqpendientes/dpto/<int:iddpto>/mes/<int:mes>/anho/<int:anho>/', views.liq_pendientes_list, name='liq_pendientes_list'),
    path('editar_liquidacion/<int:idliquidacion>/', views.vista_liq_mensual, name='editar_liquidacion'),
    path('liquidacion_haber/<int:idliquidacionhaber>/', views.vista_liquidacionhaber, name='editar_liquidacionhaber'),
    path('liquidacionhaber/<int:idliquidacionhaber>/detalle/nuevo/', views.vista_detalleliquidacion, name='detalleliquidacion-add'),
    path('liquidacionhaber/<int:idliquidacionhaber>/detalle/<int:iddetalleliq>', views.vista_detalleliquidacion,
         name='detalleliquidacion-edit'),
    path('detalle/<int:pk>/delete/', views.delete_detalleliquidacion, name='detalleliquidacion-delete'),
    path('carga_vacaciones/', views.vacaciones_form, name='cargar_vacaciones'),
    path('liquidacion/pendientes/', views.liq_pendientes_filtro, name='liq_pendientes_filtro'),
    path('liqpendientes/funcionario/<int:funcionario>/mes/<int:mes>/', views.liq_funcionarios_list, name='liq_funcionarios_list'),
    path('ajax/traer_mes/', views.traer_mes, name='traer_mes'),
    path('liquidaciones/periodo/', views.liquidaciones_periodo, name='liquidaciones_periodo'),
    path('confirmar_liquidaciones/', views.confirmar_liquidaciones, name='confirmar_liquidaciones'),
    path('consulta_vacaciones/', views.consulta_vacaciones, name='consulta_vacaciones'),
    path('liquidaciones/confirmadas/periodo/', views.confirmadas_periodo, name='confirmadas_periodo'),
    path('liquidaciond/seleccion/', views.param_liq_definitiva, name='param_liq_definitiva'),
    path('liquidacion_baja/movimiento/<int:idmovimiento>/', views.generar_liq_definitiva, name='generar_liq_definitiva'),
   # path('pdf/', GeneratePdf.as_view()),
    path('pdf/', views.generate_view, name='generate_view'),
    path('liquidacion_filtro/', views.liquidacion_filtro, name='liquidacion_filtro'),
    path('historico_movimientos/', views.historico_movimientos, name='historico_movimientos'),
    path('reporte_monto_motivo/', views.gastosxtipomovimiento, name='gastosxtipomovimiento'),
    path('informe_vacaciones/', views.informe_vacaciones, name='informe_vacaciones'),
    path('nomina_funcionarios/', views.nomina_funcionarios, name='nomina_funcionarios'),
    path('ajax/traer_departamentos/', views.traer_departamentos, name='traer_departamentos'),
    path('monto_objetodegasto/', views.monto_objetodegasto, name='monto_objetodegasto'),
    path('informe_altasbajas/', views.informe_altasbajas, name='informe_altasbajas'),
    path('print_liquidacion/<int:idliquidacion>/', views.print_liquidacion, name='print_liquidacion'),

]

sueldos/urls.py
import django.contrib
import table
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from liquidacion.views import *

urlpatterns = [
    path('', auth_views.login, name = 'login'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('liquidacion/', include('liquidacion.urls')),
    path('django_popup_view_field/', include('django_popup_view_field.urls', namespace="django_popup_view_field")),
    path('table/', include('table.urls')),
    path('home/', TemplateView.as_view(template_name='index.html'), name='home'),
]

handler404 = 'liquidacion.views.handler404'
handler500 = 'liquidacion.views.handler500'

liquidacion/forms.py
from django import forms
from django.contrib import admin
#from django.forms import *
from django.forms import ModelForm, NumberInput, IntegerField
from django.forms.widgets import SelectDateWidget, DateInput
from django.forms.fields import DateField
from liquidacion.models import *
from sueldos.settings import DATE_INPUT_FORMATS
from django.contrib.admin.widgets import AdminDateWidget
from django.contrib.postgres.forms.ranges import DateRangeField, RangeWidget
from django.forms.widgets import TimeInput

MES_OPTIONS = (
    (0 , 'Todos'),
    (1 , 'Enero'),
    (2 , 'Febrero'),
    (3 , 'Marzo'),
    (4 , 'Abril'),
    (5 , 'Mayo'),
    (6 , 'Junio'),
    (7 , 'Julio'),
    (8 , 'Agosto'),
    (9 , 'Septiembre'),
    (10 , 'Octubre'),
    (11 , 'Noviembre'),
    (12 , 'Diciembre'),
)

MES2_OPTIONS = (
    (1 , 'Enero'),
    (2 , 'Febrero'),
    (3 , 'Marzo'),
    (4 , 'Abril'),
    (5 , 'Mayo'),
    (6 , 'Junio'),
    (7 , 'Julio'),
    (8 , 'Agosto'),
    (9 , 'Septiembre'),
    (10 , 'Octubre'),
    (11 , 'Noviembre'),
    (12 , 'Diciembre'),
)

MOTIVO_OPTIONS = (
    ('Contrato', 'Contrato'),
    ('Permanente' , 'Permanente'),
)

TIPO_OPTIONS = (
    ('Alta', 'Alta'),
    ('Baja' , 'Baja'),
)


class FilroTipoMovimientoForm(forms.Form):

    desde = forms.DateTimeField(label='Desde', required=True,
                          widget=forms.TextInput(attrs={'class': 'form-control datepicker',
                                                  'id': 'fec_ini',}))

    hasta = forms.DateTimeField(label='Hasta', required=True,
                          widget=forms.TextInput(attrs={'class': 'form-control datepicker',
                                                  'id': 'fec_fin',}))

    tipo = forms.ChoiceField(label='Tipo de Movimiento', required=True, choices=TIPO_OPTIONS, widget=forms.Select(attrs={'class': 'form-control'}))


class FiltroMesForm(forms.Form):

    mes = forms.ChoiceField(label='Mes', required=True, choices=MES_OPTIONS, widget=forms.Select(attrs={'class': 'form-control',
                                                                                          'name': 'mes',
                                                                                          'id': 'mes-select',
                                                                                          }))


class FiltroDepartamentoForm(forms.Form):

    departamento = IntegerField(label='Departamento', required=True, widget=forms.Select(attrs={'class': 'form-control',
                                                                                          'name': 'departamento-select',
                                                                                          'id': 'departamento-select',
                                                                                          }))


class FiltroGastosForm(forms.Form):

    motivo = forms.ChoiceField(label='Tipo de cargo', required=True, choices=MOTIVO_OPTIONS, widget=forms.Select(attrs={'class': 'form-control',
                                                                                          'name': 'motivo',
                                                                                          'id': 'motivo-select',
                                                                                          }))

    anho = forms.IntegerField(label='Año', required=True, widget=forms.NumberInput(attrs={'class': 'form-control',
                                                                                          'name': 'anho',
                                                                                          }))


class LiquidacionDefinitivaForm(forms.Form):

    funcionario = IntegerField(label='Nro. de Documento de Identidad', required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'placeholder' : "Ingrese el número de documento",}))

class VacacionesFuncionarioForm(forms.Form):

    funcionario = IntegerField(label='Nro. de Documento de Identidad', required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'placeholder' : "Ingrese el numero de documento de identidad"}))


class LiqPendientesForm(forms.Form):

    funcionario = forms.CharField(label='Funcionario', required=True, widget=forms.TextInput(attrs={'class': 'form-control',
                                                              'name': 'funcionario',
                                                              }))

    mes = forms.ChoiceField(label='Mes', required=True, choices=MES2_OPTIONS, widget=forms.Select(attrs={'class': 'form-control',
                                                                                          'name': 'mes',
                                                                                          'id': 'mes-select',
                                                                                          }))

    anho = forms.IntegerField(label='Año', required=True, widget=forms.NumberInput(attrs={'class': 'form-control',
                                                                                          'name': 'anho',
                                                                                          }))

class VacacionesusadasForm(forms.ModelForm):
    class Meta:
        model = Vacacionesusadas
        exclude = ['vacaciones']
        widgets = {
            'diasusados': forms.NumberInput(attrs={
                'class': 'form-control',
            }),
        }


class DetalleLiquidacionForm(forms.ModelForm):
    class Meta:
        model = DetalleLiquidacion
        exclude = ['liquidacion','total', 'salario_proporcional', 'pago']
        widgets = {
            'variable': forms.Select(attrs={
                'class': 'form-control',
            }),
            'parametro': forms.Select(attrs={
                'class': 'form-control',
            }),
            'cantidad': forms.NumberInput(attrs={
                'class': 'form-control',
            }),
            'monto': forms.NumberInput(attrs={
                'class': 'form-control',
            }),
        }


class LiquidacionhaberForm(forms.ModelForm):
    class Meta:
        model = Liquidacionhaber
        fields = '__all__'


class LiqMensualForm(forms.ModelForm):
    class Meta:
        model = Liquidacion
        exclude = ['ultimamodificacion' ,'propietario', 'tipo', 'haberes']
        widgets = {
            'vacaciones_usadas': forms.NumberInput(attrs={
                'class': 'form-control',
                'size' : "30",
            }),
            'motivo': forms.Select(attrs={
                'class': 'form-control',
            }),
        }


class PreLiqMensualForm(forms.Form):

    desde = forms.DateTimeField(label='Desde', required=True,
                          widget=forms.TextInput(attrs={'class': 'form-control datepicker',
                                                  'id': 'fec_ini',}))

    hasta = forms.DateTimeField(label='Hasta', required=True,
                          widget=forms.TextInput(attrs={'class': 'form-control datepicker',
                                                  'id': 'fec_fin',}))

    departamento = forms.IntegerField(label='Departamento', required=True, widget=forms.Select(attrs={'class': 'form-control',
                                                                                          'name': 'departamento',
                                                                                          'id': 'departamento-select',
                                                                                          }))

class FuncionarioForm(forms.ModelForm):
    class Meta:
        model = Funcionario
        fields = '__all__'
        widgets = {
            'usuario': forms.Select(attrs={
                'class': 'form-control',
            }),
        }


class MovimientoForm(forms.ModelForm):
    class Meta:
        model = Movimiento
        exclude = ['movimiento_padre','funcionario','estado','esPrimero', 'familia']
        widgets = {
            'codigo': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'categoria_salarial': forms.TextInput(attrs={
                'type': 'hidden',
                'class': 'form-control'
            }),
            'og': forms.Select(attrs={
                'class': 'form-control'
            }),
            'tipo': forms.Select(attrs={
                'class': 'form-control'
            }),
            'motivo': forms.Select(attrs={
                'class': 'form-control'
            }),
            'formapago': forms.Select(attrs={
                'class': 'form-control'
            }),
            'ffinanciamiento': forms.Select(attrs={
                'class': 'form-control'
            }),
            'division': forms.Select(attrs={
                'class': 'form-control'
            }),
            'funcion': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'fechainicio': forms.DateInput(attrs={
                'type': 'date',
                'class': 'form-control',
            }),
            'fechafin': forms.DateInput(attrs={
                'type' : 'date',
                'class': 'form-control',
                'readonly': True
            }),
            'horaEntrada': forms.TimeInput(attrs={
                'class': 'form-control',
                'readonly': True
            }),
            'horaSalida': forms.TimeInput(attrs={
                'class': 'form-control',
                'readonly': True
            }),
            'tieneAguinaldo': forms.CheckboxInput(attrs={
                'class': 'form-control'
            }),
            'tieneVacaciones': forms.CheckboxInput(attrs={
                'class': 'form-control'
            }),

templates/constante/constante_form.html
{% extends "proceso/movimiento_form.html" %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
{% load humanize %}

{% block navbar %}
    <li class="nav-item">
    <a id="" data-toggle="modal" data-target="#help_modal" class="nav-link text-center">
        <i class="fa fa-question-circle"></i> Ayuda</a>
    </li>
{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Debitos y Creditos" 'liquidacion:nueva_constante' %}
{% endblock %}

{% block content %}
{% render_breadcrumbs %}

<div class="col-12 col-sm-10 recuadro">

<form method="post" id="constante_form">
        {% csrf_token %}

        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link" href='{% url 'liquidacion:editar_movimiento' movimiento.pk %}'>Movimiento N° {{ movimiento.pk }}</a>
            </li>
            <li class="nav-item">
                {% if movimiento.motivo.nombre == 'Contrato' %}
                    <a class="nav-link" href="{% url 'liquidacion:nuevo_pago' movimiento.pk %}">
                        Pagos
                    </a>
                {% else %}
                    <a class="nav-link active" style="background-color: #b9bbbe" href="{% url 'liquidacion:nueva_constante' movimiento.pk %}">
                        Debitos y Creditos
                    </a>
                {% endif %}
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Documento</a>
                <div class="dropdown-menu">
                    {% if documento %}
                        <a class="dropdown-item" onclick="return abrir_modal('{% url 'liquidacion:ver_documento' documento.movimiento.pk documento.pk %}')">Ver documento</a>
                    {% else %}
                        <button class="dropdown-item btn btn-link" onclick="return abrir_modal('{% url 'liquidacion:nuevo_documento' movimiento.pk %}')">Crear Nuevo</button>
                    {% endif %}
                </div>
            </li>
        </ul>

        <div class="row text-center">
            <div class="col-12 text-center">
                <h4>Alta de Funcionario</h4>
                <h5><strong>Debitos y Creditos de Salario</strong></h5>
            </div>
        </div>
        <br>
        <div class="row"> <!-- cabecera-->
            <div class="col-12">
                <div class="row">
                    <div class="col-6">
                        <ul class="list-inline">
                            {% if movimiento %}
                                <li class="list-inline-item">Funcionario: <strong>{{ movimiento.funcionario }}</strong></li>
                                <li class="list-inline-item">Categoria Salarial: <strong>{{ movimiento.categoria_salarial.codigo }}</strong></li>
                            {% else %}
                                <li class="list-inline-item">Funcionario: <strong>{{ funcionario }}</strong></li>
                            {% endif %}
                        </ul>
                    </div>
                    <div class="col-4">
                        <ul class="list-inline">
                            {% if movimiento %}
                                <li class="list-inline-item">Cargo: <strong>{{ movimiento.categoria_salarial.cargo }}</strong></li>
                                <li class="list-inline-item">Departamento: <strong>{{ movimiento.division.departamento }}</strong></li>
                            {% else %}
                                <li class="list-inline-item">Funcionario: <strong>{{ funcionario }}</strong></li>
                            {% endif %}
                        </ul>
                    </div>
                    <div class="col-2 d-flex justify-content-end align-items-center">
                        <div class="row separador"></div>
                        <button type="button" class="btn btn-secondary" name="finalizar"
                                onclick="location.href='{% url 'liquidacion:movimiento_resumen' movimiento.pk %}'">
                            Finalizar
                        </button>
                    </div>
                </div>
            </div>
        </div>

    <!-- Fin cabecera -->
        <hr>
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    <label for="tipo">Tipo:</label>
                    <div class="input-group">
                        {{ form.tipo }}
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="form-group">
                    <label for="monto">Monto:</label>
                    <div class="input-group">
                        {{ form.monto }}
                    </div>
                </div>
            </div>
            <div class="col-lg-2">
                <div class="form-group">
                    <label for="monto"></label>
                    <div class="input-group">
                        <button type="submit" class="btn btn-success" name="guardar"
                        formaction="{% url 'liquidacion:nueva_constante' movimiento.pk %}">
                            Agregar
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                {% for message in messages %}
                    <div class="alert alert-danger">{{ message }}
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    </div>
                {% endfor %}
            </div>
        </div>
</form>
<hr>

<div class="row">
    <div class="col-lg-12">
        <table id="tabla_constantes" class="table table-hover">
            <thead class="thead-light">
                <tr>
                    <th class="text-center">Descripcion</th>
                    <th class="text-center">Tipo</th>
                </tr>
            </thead>
            <tbody>
                {% for constante in constantes %}
                    <tr class='clickable-row'>
                        <td>{{ constante.tipo.nombre }}</td>
                        <td class="text-center">{{ constante.tipo.tipo }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<div id="help_modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" style="background-color: #b9bbbe">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold" style="color: #007bff">Información de ayuda al usuario</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>En ésta sección usted podrá agregar al nuevo cargo, los montos que se debitarán o acreditarán al
                    salario del funcionario indefinidamente durante el tiempo que dure activo en el cargo.
                    Aquí usted deberá seleccionar el concepto correspondiente a dicho monto seleccionando una
                    opción en el campo <strong>Tipo</strong>,
                    en caso de que el concepto sea calculado en base a un porcentaje del salario, éste se mostrará
                    entre las opciones a seleccionar, de lo contrario usted podrá especificar en el campo
                    <strong>Monto</strong> una cantidad fija en Guaraníes, la cual se aplicará indefinidamente al salario del funcionario
                    según el tipo del concepto que seleccione, que podrá ser tanto débito como crédito.
                </p>
                <p>Para finalizar el proceso presione el botón
                    <button type="button" class="btn btn-secondary" name="finalizar" onclick="">Finalizar</button>
                </p>
            </div>
            <div id="modal-body" class="modal-footer">
                <button type="button" class="btn btn-primary btn-block" data-dismiss="modal">Entendido</button>
            </div>
        </div>
    </div>
</div>

</div>

<div id="popup" class="modal fade" role="dialog">

</div>

<script>
function abrir_modal(url)
{
        $('#popup').load(url, function()
        {
                $(this).modal('show');
        });
        return false;
}

function cerrar_modal()
{
        $('#popup').modal('hide');
        return false;
}

$(document).ready(function () {
        $("#cantidad_veces").hide();
        $('#finito').on('change', function (e) {
            if($('#finito').is(":checked"))
                $("#cantidad_veces").show();
            else
                $("#cantidad_veces").hide();
        });
    });



$('#id_tipo').change(function () {
    var select = document.getElementById('id_tipo');
    var options = select.options;
    var selected = select.options[select.selectedIndex];
    if (selected.innerHTML.includes("%")) {
        console.log("YES", selected.innerHTML);
         $('#id_monto').prop('disabled',true);
    } else {
         $('#id_monto').prop('disabled',false);
    }
});


</script>

{% endblock %}