liquidacion/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.views.i18n import JavaScriptCatalog

from liquidacion.views import *
from . import views

app_name = 'liquidacion'

urlpatterns = [
    #path('accounts/login/', 'django.contrib.auth.views.login', name='login'),
    #path('accounts/logout/', 'django.contrib.auth.views.logout', name='logout'),
    path('home/', views.index, name='index'),
    path('opciones_proceso', views.opciones_proceso, name='opciones_proceso'),
    path('opciones_vacaciones', views.opciones_vacaciones, name='opciones_vacaciones'),
    path('opciones_reportes', views.opciones_reportes, name='opciones_reportes'),
    path('funcionario/<int:idfuncionario>/movimiento/nuevo/', views.movimiento_vista, name='nuevo_movimiento'),
    path('movimiento_padre/<int:idpadre>/', views.movimiento_vista, name='modificar_movimiento'),
    path('movimiento/<int:idmovimiento>', views.movimiento_vista, name='editar_movimiento'),
    path('buscar_funcionario', views.busqueda_funcionarios, name='buscar_funcionario'),
    path('buscar_movimiento', views.busqueda_movimiento_funcionario, name='buscar_movimiento'),
    path('get_movimientos', views.get_movimientos, name='get_movimientos'),
    path('movimiento/<int:idmovimiento>/documento/nuevo/', views.documento_vista, name='nuevo_documento'),
    path('movimiento/<int:idmovimiento>/documento/<int:iddocumento>', views.documento_vista, name='ver_documento'),
    path('movimiento/<int:idmovimiento>/constante/nuevo/', views.constante_vista, name='nueva_constante'),
    path('movimiento/<int:idmovimiento>/constante/<int:idconstante>', views.constante_vista, name='borrar_constante'),
    path('categoriasalarial-list', CategoriaSalarialList.as_view(), name='categoriasalarial-list'),
    path('objetodegasto/add/', ObjetoDeGastoCreate.as_view(), name='objetodegasto-add'),
    path('tipomovimiento/add/', TipoMovimientoCreate.as_view(), name='tipomovimiento-add'),
    path('movimientomotivo/add/', MovimientoMotivoCreate.as_view(), name='movimientomotivo-add'),
    path('success_page/<int:idmovimiento>/', views.success_page, name='success_page'),
    path('movimiento_resumen/<int:idmovimiento>/', views.mostrar_movimiento_resumen, name='movimiento_resumen'),
    path('ajax/traer_tipomovimientos/', views.traer_tipomovimientos, name='traer_tipomovimientos'),
    path('ajax/traer_og/', views.traer_og, name='traer_og'),
    path('ajax/traer_variables/', views.traer_variables, name='traer_variables'),
    path('ajax/traer_constantes/', views.traer_constantes, name='traer_constantes'),
    path('ajax/traer_motivomovimientos/', views.traer_motivomovimientos, name='traer_motivomovimientos'),
    path('buscarmovimientofuncionario/', views.buscar_movimientos_funcionario, name='buscar_movimientos_funcionario'),
    path('movimiento/<int:idmovimiento>/pago/nuevo/', views.pago_vista, name='nuevo_pago'),
    path('liquidacionm/seleccion/', views.parametros_liq_mensual, name='parametros_liq_mensual'),
    path('ajax/traer_departamentos/', views.traer_departamentos, name='traer_departamentos'),
    path('ajax/traer_funcionarios/', views.traer_funcionarios, name='traer_funcionarios'),
    path('liqpendientes/dpto/<int:iddpto>/mes/<int:mes>/anho/<int:anho>/', views.liq_pendientes_list, name='liq_pendientes_list'),
    path('editar_liquidacion/<int:idliquidacion>/', views.vista_liq_mensual, name='editar_liquidacion'),
    path('liquidacion_haber/<int:idliquidacionhaber>/', views.vista_liquidacionhaber, name='editar_liquidacionhaber'),
    path('liquidacionhaber/<int:idliquidacionhaber>/detalle/nuevo/', views.vista_detalleliquidacion, name='detalleliquidacion-add'),
    path('liquidacionhaber/<int:idliquidacionhaber>/detalle/<int:iddetalleliq>', views.vista_detalleliquidacion,
         name='detalleliquidacion-edit'),
    path('detalle/<int:pk>/delete/', views.delete_detalleliquidacion, name='detalleliquidacion-delete'),
    path('carga_vacaciones/', views.vacaciones_form, name='cargar_vacaciones'),
    path('liquidacion/pendientes/', views.liq_pendientes_filtro, name='liq_pendientes_filtro'),
    path('liqpendientes/funcionario/<int:funcionario>/mes/<int:mes>/', views.liq_funcionarios_list, name='liq_funcionarios_list'),
    path('ajax/traer_mes/', views.traer_mes, name='traer_mes'),
    path('liquidaciones/periodo/', views.liquidaciones_periodo, name='liquidaciones_periodo'),
    path('confirmar_liquidaciones/', views.confirmar_liquidaciones, name='confirmar_liquidaciones'),
    path('consulta_vacaciones/', views.consulta_vacaciones, name='consulta_vacaciones'),
    path('liquidaciones/confirmadas/periodo/', views.confirmadas_periodo, name='confirmadas_periodo'),
    path('liquidaciond/seleccion/', views.param_liq_definitiva, name='param_liq_definitiva'),
    path('liquidacion_baja/movimiento/<int:idmovimiento>/', views.generar_liq_definitiva, name='generar_liq_definitiva'),
   # path('pdf/', GeneratePdf.as_view()),
    path('pdf/', views.generate_view, name='generate_view'),
    path('liquidacion_filtro/', views.liquidacion_filtro, name='liquidacion_filtro'),
    path('historico_movimientos/', views.historico_movimientos, name='historico_movimientos'),
    path('reporte_monto_motivo/', views.gastosxtipomovimiento, name='gastosxtipomovimiento'),
    path('informe_vacaciones/', views.informe_vacaciones, name='informe_vacaciones'),
    path('nomina_funcionarios/', views.nomina_funcionarios, name='nomina_funcionarios'),
    path('ajax/traer_departamentos/', views.traer_departamentos, name='traer_departamentos'),
    path('monto_objetodegasto/', views.monto_objetodegasto, name='monto_objetodegasto'),
    path('informe_altasbajas/', views.informe_altasbajas, name='informe_altasbajas'),
    path('print_liquidacion/<int:idliquidacion>/', views.print_liquidacion, name='print_liquidacion'),

]

sueldos/urls.py
import django.contrib
import table
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from liquidacion.views import *

urlpatterns = [
    path('', auth_views.login, name = 'login'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('liquidacion/', include('liquidacion.urls')),
    path('django_popup_view_field/', include('django_popup_view_field.urls', namespace="django_popup_view_field")),
    path('table/', include('table.urls')),
    path('home/', TemplateView.as_view(template_name='index.html'), name='home'),
]

handler404 = 'liquidacion.views.handler404'
handler500 = 'liquidacion.views.handler500'

templates/base.html
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
{% load django_popup_view_field_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SLSB-FPUNA</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- Bootstrap core CSS-->
    <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="{% static "vendor/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
    <!-- Page level plugin CSS-->
    <link href="{% static "vendor/datatables/dataTables.bootstrap4.css" %}" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="{% static "css/sb-admin.css" %}" rel="stylesheet">
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    {% block extrastyles %}{% endblock %}
</head>


<body class="fixed-nav bg-dark" id="page-top">
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="{% url 'liquidacion:index' %}">Sistema de liquidacion de Salarios y Beneficios</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
 <div class="collapse navbar-collapse" id="navbarResponsive">
  <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
      <a class="nav-link" href="{% url 'liquidacion:index' %}">
        <span class="nav-link-text">Inicio</span>
      </a>
    </li>
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">

    </li>
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Charts">

    </li>
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">

    </li>
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Components">

    </li>
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Example Pages">

    </li>
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Menu Levels">

    </li>
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">

    </li>
  </ul>
  <ul class="navbar-nav sidenav-toggler">
    <li class="nav-item">
      <a class="nav-link text-center" id="sidenavToggler">
        <i class="fa fa-fw fa-angle-left"></i>
      </a>
    </li>
  </ul>
  <ul class="navbar-nav ml-auto">
    {% block navbar %}
    {% endblock %}
    {% if user.is_authenticated %}
        <li class="nav-item">
          <p class="nav-link">
            <i class="fa fa-fw fa-user"></i>Bienvenido, <strong>{{ user.username }}</strong></p>
        </li>
    {% endif %}
    <li class="nav-item">
      <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
        <i class="fa fa-fw fa-sign-out"></i>Salir</a>
    </li>
  </ul>
</div>
  </nav>
  <div class="content-wrapper" style="background-image: url({% static 'img/fondo.png' %})">
    <div class="container-fluid">
    {% block breadcrumbs %}
        {% clear_breadcrumbs %}
        {% breadcrumb " Inicio " 'liquidacion:index' %}
    {% endblock %}

    {% block content %}
    {% render_breadcrumbs %}
    {% endblock %}
    </div>
    <!-- /.container-fluid-->
    <!-- /.content-wrapper}
    <footer class="sticky-footer">
      <div class="container">
        <div class="text-center">
          <small>

          </small>
        </div>
      </div>
    </footer>-->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Seguro que desea cerrar sesion?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
            <a class="btn btn-primary" href="{% url 'logout' %}">Confirmar</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
<footer>
<!-- Bootstrap core JavaScript-->
    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static "vendor/jquery-easing/jquery.easing.min.js" %}"></script>

    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>  <!-- JQUERY HERE -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Page level plugin JavaScript-->
    <script src="{% static "vendor/chart.js/Chart.min.js" %}"></script>
    <script src="{% static "vendor/datatables/jquery.dataTables.js" %}"></script>
    <script src="{% static "vendor/datatables/dataTables.bootstrap4.js" %}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{% static "js/sb-admin.min.js" %}"></script>
    <!-- Custom scripts for this page-->
    <script src="{% static "js/sb-admin-datatables.min.js" %}"></script>
    <script src="{% static "js/sb-admin-charts.min.js" %}"></script>
    {% django_popup_view_field_javascript %}
</footer>

</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load admin_urls %}

{% block content %}
    <div class="row">
        <div class="col-xl-3 col-sm-6 mb-3">
          <div class="card text-white bg-primary o-hidden h-100">
            <div class="card-body">
              <div class="card-body-icon">
                <i class="fa fa-fw fa-cog"></i>
              </div>
              <div class="mr-5" style="font-weight: bold">Administración del Sistema</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="{% url 'admin:index' %}">
              <span class="float-left"></span>
              <span class="float-right">
                <i class="fa fa-angle-right"></i>
              </span>
            </a>
          </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-3">
          <div class="card text-white bg-warning o-hidden h-100">
            <div class="card-body">
              <div class="card-body-icon">
                <i class="fa fa-fw fa-address-card"></i>
              </div>
              <div class="mr-5" style="font-weight: bold">Liquidacion Salarial y Beneficios</div>
            </div>
            <a class="card-footer text-white clearfix small z-1"
               onclick="return abrir_modal('{% url 'liquidacion:opciones_proceso' %}')">
              <span class="float-left"></span>
              <span class="float-right">
                <i class="fa fa-angle-right"></i>
              </span>
            </a>
          </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-3">
          <div class="card text-white bg-success o-hidden h-100">
            <div class="card-body">
              <div class="card-body-icon">
                <i class="fa fa-fw fa-inbox"></i>
              </div>
              <div class="mr-5" style="font-weight: bold">Informes y Consulta de Datos</div>
            </div>
            <a class="card-footer text-white clearfix small z-1"
               onclick="return abrir_modal('{% url 'liquidacion:opciones_reportes' %}')">
              <span class="float-left"></span>
              <span class="float-right">
                <i class="fa fa-angle-right"></i>
              </span>
            </a>
          </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-3">
          <div class="card text-white bg-secondary o-hidden h-100">
            <div class="card-body">
              <div class="card-body-icon">
                <i class="fa fa-fw fa-calendar-o"></i>
              </div>
              <div class="mr-5" style="font-weight: bold">Vacaciones</div>
            </div>
            <a class="card-footer text-white clearfix small z-1"
               onclick="return abrir_modal('{% url 'liquidacion:opciones_vacaciones' %}')">
              <span class="float-left"></span>
              <span class="float-right">
                <i class="fa fa-angle-right"></i>
              </span>
            </a>
          </div>
        </div>
    </div>


<div id="popup" class="modal fade" role="dialog"></div>

<script>
    function abrir_modal(url)
    {
        $('#popup').load(url, function()
        {
                $(this).modal('show');
        });
        return false;
    }

    function cerrar_modal()
    {
        $('#popup').modal('hide');
        return false;
    }

</script>

{% endblock %}

templates/movimientomotivo_form.html
{% block content %}
{% include 'movimientomotivo_form_inner.html' %}
{% endblock %}

templates/movimientomotivo_form_inner.html
<div id="form-modal-body" class="modal-body">
    <form id="motivomov_form" class="form-horizontal" method="post" action="{% url 'liquidacion:movimientomotivo-add' %}">
        {% csrf_token %}
        <div class="form-group">
            {% if form.nombre.errors %}
                    {% for error in form.nombre.errors %}
                        <div class="errorlist">
                            <strong style="color: red">{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
            <label for="nombre">Descripcion:</label>
            <div class="input-group">
               {{ form.nombre }}
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
            <button type="submit" id="submitForm" class="btn btn-primary btn-block">Guardar</button>
            </div>
        </div>
    </form>
</div>


<script>
    $(document).ready(function () {
        $('#motivomov_form').on("submit", function(e) {
            e.preventDefault();
            $.ajax({
             type: $(this).attr('method'),
              url: $(this).attr('action'),
             data: $(this).serialize(),
             success: function (xhr, ajaxOptions, thrownError) {
                 if ( $(xhr).find('.errorlist').length > 0 ) {
                    $('#motivomov_modal').find('.modal-body').html(xhr);
                } else {
                     $('#motivomov_modal').find('.modal-body').html('Los datos se han creado correctamente!');
                }
            },
              error: function (xhr, ajaxOptions, thrownError) {
                 console.log('Entra al else');
                 // handle response errors here
            }
        });
    });

    $("#submitForm").on('click', function() {
		$("#motivomov_form").submit();
	});
 });
</script>

templates/objetodegasto_form.html
{% block content %}
{% include 'objetodegasto_form_inner.html' %}
{% endblock %}

templates/objetodegasto_form_inner.html
<div id="form-modal-body" class="modal-body">
    <form id="og_form" class="form-horizontal" method="post" action="{% url 'liquidacion:objetodegasto-add' %}">
        {% csrf_token %}
        <div class="form-group">
            {% if form.numero.errors %}
                {% for error in form.numero.errors %}
                    <div class="errorlist">
                        <strong style="color: red">{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
            <label for="numero">Numero:</label>
            <div class="input-group">
               {{ form.numero }}
            </div>
        </div>
        <div class="form-group">
            {% if form.concepto.errors %}
                {% for error in form.concepto.errors %}
                    <div class="errorlist">
                        <strong style="color: red">{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
        <label for="concepto">Concepto:</label>
        <div class="input-group">
            {{ form.concepto }}
        </div>
        </div>
        <div class="form-group">
            <div class="input-group">
            <button type="submit" id="submitForm" class="btn btn-primary btn-block">Guardar</button>
            </div>
        </div>
    </form>
</div>


<script>
    $(document).ready(function () {
        $('#og_form').on("submit", function(e) {
            e.preventDefault();
            $.ajax({
             type: $(this).attr('method'),
              url: $(this).attr('action'),
             data: $(this).serialize(),
             success: function (xhr, ajaxOptions, thrownError) {
                 if ( $(xhr).find('.errorlist').length > 0 ) {
                    $('#og_modal').find('.modal-body').html(xhr);
                } else {
                     $('#og_modal').find('.modal-body').html('Los datos se han creado correctamente!');
                }
            },
              error: function (xhr, ajaxOptions, thrownError) {
                 console.log('Entra al else');
                 // handle response errors here
            }
        });
    });

    $("#submitForm").on('click', function() {
		$("#og_form").submit();
	});
 });
</script>

templates/pago_form.html
{% extends "proceso/movimiento_form.html" %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
{% load humanize %}

{% block navbar %}
    <li class="nav-item">
    <a id="" data-toggle="modal" data-target="#help_modal" class="nav-link text-center">
        <i class="fa fa-question-circle"></i> Ayuda</a>
    </li>
{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Agregar Pagos" 'liquidacion:nuevo_pago' %}
{% endblock %}

{% block content %}
{% render_breadcrumbs %}

<div class="col-12 col-sm-10 recuadro">

<form method="post" id="pago_form">
        {% csrf_token %}

        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link" href='{% url 'liquidacion:editar_movimiento' movimiento.pk %}'>Movimiento N° {{ movimiento.pk }}</a>
            </li>
            <li class="nav-item">
                {% if movimiento.motivo.nombre == 'Contrato' %}
                    <a class="nav-link active" style="background-color: #b9bbbe" href="{% url 'liquidacion:nuevo_pago' movimiento.pk %}">
                        Pagos
                    </a>
                {% else %}
                    <a class="nav-link" href="{% url 'liquidacion:nueva_constante' movimiento.pk %}">
                        Debitos y Creditos
                    </a>
                {% endif %}
            </li>
        </ul>
        <br>
        <div class="row text-center">
            <div class="col-12 text-center">
                <h4>Creación de Alta de Funcionario</h4>
            </div>
        </div>
        <br>
        <div class="row"> <!-- cabecera-->
            <div class="col-12">
                <div class="row">
                    <div class="col-10">
                        <ul class="list-inline">
                            {% if movimiento %}
                                <li class="list-inline-item">Funcionario: <strong>{{ movimiento.funcionario }}</strong></li>
                            {% else %}
                                <li class="list-inline-item">Funcionario: <strong>{{ funcionario }}</strong></li>
                            {% endif %}
                        </ul>
                    </div>
                    <div class="col-2 d-flex justify-content-end align-items-center">
                        <div class="row separador"></div>
                        <button type="button" class="btn btn-secondary" name="finalizar"
                                onclick="location.href='{% url 'liquidacion:movimiento_resumen' movimiento.pk %}'">
                            Finalizar
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="row"> <!-- cabecera-->
            <div class="col-10 d-flex align-items-center">
                <span class="h4">Pagos del Contrato N° {{ movimiento.codigo }}</span>
            </div>

        </div>
    <!-- Fin cabecera -->
        <br>
        <div class="row">
            <div class="col-lg-5">
                <div class="form-group">
                    <label for="mes">Mes:</label>
                    <div class="input-group">
                        {{ form.mes }}
                    </div>
                </div>
            </div>
            <div class="col-lg-5">
                <div class="form-group">
                    <label for="monto">Monto (En Guaraníes):</label>
                    <div class="input-group">
                        {{ form.monto }}
                    </div>
                </div>
            </div>
            <div class="col-2 d-flex justify-content-end align-items-center">
                <div class="row separador"></div>
                <button type="submit" class="btn btn-success" name="guardar"
                        formaction="{% url 'liquidacion:nuevo_pago' movimiento.pk %}">
                    Agregar
                </button>
            </div>
        </div>
</form>
<div class="row">
    <div class="col-lg-12">
        {% for message in messages %}
            <div class="alert alert-danger">{{ message }}
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            </div>
        {% endfor %}
    </div>
</div>

{% if pagos %}
<hr>

<div class="row">
        <div class="col-lg-12">
        <table id="tabla_pagos" class="table table-hover">
            <thead class="thead-light">
                <tr>
                    <th class="text-center">Mes</th>
                    <th class="text-center">Monto</th>
                </tr>
            </thead>
            <tbody>
                {% for pago in pagos %}
                    <tr class='clickable-row'>
                        <td class="text-center">{{ pago.mes }}</td>
                        <td class="text-center">Gs. {{ pago.monto|floatformat }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
{% endif %}

</div>

<div id="help_modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" style="background-color: #b9bbbe">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold" style="color: #007bff">Ayuda a usuario</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>En esta sección usted podrá agregar pagos al contrato creado según lo estipulado en el mismo.
                    Para el efecto seleccione el mes del año y en el campo <strong>Monto</strong> ingrese
                    el monto en Guaraníes correspondiente al mes en el cual se efectuará dicho pago.</p>
                <p>Para guardar los datos presione el botón
                    <button type="submit" class="btn btn-success" name="guardar" formaction="">Agregar</button> y
                    automáticamente se agregará el pago al contrato.</p>
                <p>Para finalizar el proceso presione el botón
                    <button type="button" class="btn btn-secondary" name="finalizar" onclick="">Finalizar</button>
                </p>
            </div>
            <div id="modal-body" class="modal-footer">
                <button type="button" class="btn btn-primary btn-block" data-dismiss="modal">Entendido</button>
            </div>
        </div>
    </div>
</div>

<div id="popup" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">

</div>

<footer>
    <script>
        $(document).ready(function (event) {
            var mes_select = $('#mes-select');
            $.ajax({
                url: '{% url 'liquidacion:traer_mes' %}',
                dataType: 'json',
                data: {},
                success: function (data) {
                    if ($.trim(data)) {
                        mes_select.empty().append('<option value=' + 0 + ' selected >' + 'Todos' + '</option>');
                        $.each(data, function (key, value) {
                            mes_select.append('<option value=' + value.id + '>' + value.value + '</option>')
                        });
                    } else {
                        mes_select.empty().append('<option value=' + 0 + ' selected>' + 'Todos' + '</option>');
                    }
                },
                error: function (data) {
                    mes_select.empty().append('<option value=' + 0 + ' selected disabled="true">' + 'No hay datos' + '</option>');
                }
            })
        });
    </script>

</footer>


{% endblock %}

templates/success_page.html
{% extends "proceso/movimiento_form.html" %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
{% load l10n %}

{% block content %}

<div class="col-12 col-sm-10 recuadro">
<div>
    <strong>
        Proceso completado con exito!
    </strong>
</div>
<hr>
<div class="row">

    {% if tipo == 'Contrato' %}
        <div class="col-md-4 text-left">
		   <button type="submit" id="submitForm" class="btn btn-primary"
                    onclick="location.href='{% url 'liquidacion:nuevo_pago' idmovimiento %}'">Agregar Pagos</button>
        </div>
    {% else %}
        <div class="col-md-4 text-center">
		   <button type="submit" id="submitForm" class="btn btn-primary"
           onclick="location.href='{% url 'liquidacion:nueva_constante' idmovimiento %}'">Agregar Debitos y Creditos</button>
        </div>
    {% endif %}
    <div class="col-md-4 text-right">
        <button type="submit" id="submitForm" class="btn btn-primary"
               onclick="location.href='{% url 'liquidacion:movimiento_resumen' idmovimiento %}'">Ver</button>
    </div>
  </div>
</div>
{% endblock %}